repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.2
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.4.30
  hooks:
    - id: uv-lock
    - id: uv-export
